### ISSUE TITLE
"Bayes-optimal estimation of overlap between populations of fixed size"

### ISSUE THREAD

**Issue by mathieuboudreau** [Notebook-Factory/assign#2]
Paper: https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1006898 
Code: https://github.com/dblarremore/BayesianRepertoireOverlap/
Note: Python 3, Jupyter notebooks, but reproduces all figures from paper.

**Comment by mathieuboudreau** [comment]
# To-Do (Create Plotly Figures)

* [x] ~Figure 1~ 
  * Missing in notebooks
* [x] Figure 2
* [x] Figure 3

* [x] Figure 4
* [x] Figure 5
  * [x] a)
  * [x] b)
  * [x] c)
  * [x] d)
* [x] Figure 6

**Comment by mathieuboudreau** [comment]
# To do (Format figures like paper)

* [x] ~Figure 1~ 
  * Missing in notebooks
* [x] Figure 2
  * [x] Fix "90% cred" name
  * [x] Reorder figure labels to match paper
  * [x] "Estimate" remove capital "E"
* [x] Figure 3
  * [x] (y axis labels) "s" should have a circumflex, if possible.
    * replace s with \u015D
  * [x] Try and move drop down to the position where those names are in the original figure (top left inside the figure)
  * [x] Move legend more to bottom right.
  * [x] Change color of reference line to black
  * [x] If possible, remove reference from legend
  * [x] Match colors of datasets to Figure 4
* [x] Figure 4
  * [x] (y axis labels) "s" should have a circumflex, if possible.
    * replace s with \u015D
  * [x] Try and move drop down to the position where those names are in the original figure (top left inside the figure)
  * [x] Move legend more to bottom right.
  * [x] Change color of reference line to black
  * [x] If possible, remove reference from legend
* [ ] Figure 5
  * [ ] For a & b
     * [x] Move dropdown higher so it doesn't overlap
     * [x] Add border lines around x and y
     * [x] Write comment on plotly issue to remind them
     * [ ]  Show y label for default option
  * [ ] For c & d
    * [ ] Show y label for default option
    * [ ] Show y labels when selecting options
  * [x] a)
  * [x] b)
  * [ ] c)
  * [ ] d)
    * [ ] Change x-range to be the same as c), and we'll tell authors about it.
* [x] Figure 6
  * [x] Make drop down default to 48 colonies
     * If needed, add an if statement in the for loop to make all idx < 10 false
  * [x] Reduce the size of the Y axis by about half
  * [x] Add borders to the bar plot boxes, if possible
  * [x] (x and y axis labels) "s" should have a circumflex, if possible.
    * replace s with \u015D
  * [x] Try and move drop down to the position where those names are in the original figure (top left inside the figure, but a little bit higher than the plot entries)
  * [x] Typo in "Estimatet"
  * [ ] x-axis label, comma before "s" is needed.

**Comment by mathieuboudreau** [comment]
# To Do (Format Jupyter Book)

* [ ] Introduction
  * [ ] Typo in paper title "Bayes" not "TBayes".
  * [ ] Give full citation for paper and not just title, something like :  "Welcome to an interactive Jupyter Book for the research paper: [*Larremore DB (2019) Bayes-optimal estimation of overlap between populations of fixed size. PLOS Computational Biology 15(3): e1006898.*](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1006898)"
  * [ ] Replace "This Jupyter Book lets you interact with a demo of their code. " with "This Jupyter Book reproduces their paper figures, and lets you interact with them".
   * [ ] Make "PLOS COMPUTATIONAL BIOLOGY" logo and put it at the bottom
* [ ] Abstract
   * [ ] First affiliation has an extra "1" to be removed
* [ ] Add external link to the sidebar to the paper

* [ ] Remove all old static matplotlib figures & code
* [ ] Split figures into different pages to speed up loading times
  * This might be annoying because data is all processed in the same scripts, so we might need to brainstorm alternative ideas too @agahkarakuzu @TommyBoshkovski .
* [ ] Hide all code above figures
* [ ] Split code like this (with hidden cells)
  * Cell 1: Imports
  * Cell 2: functions
  * Cell 3: Whatever other code is needed to create the data for the figure
  * Cell 4: figure code

**Comment by mathieuboudreau** [comment]
# Notes from June 30th meeting

To do:

* [ ] Fix image widths for figures 2, 3, and 6.
* [ ] Create figure 5
  * Box plots should be easy, good documentation on Plotly
  * Flipped histograms should also not pose a problem, just switch x and y data from traditional histograms.

Later on to-do (after figures have been formatted...
* Split figures into different Jupyter pages

**Comment by zelenkastiot** [comment]
For displaying **Plotly** figures in Binder, type this if you want to plot it inside the jupyter notebook:  

```Python
# BINDER
iplot(figure,config=config)
```

**Comment by FilipVel** [comment]
Guys, just wanted to let you know I've done everything we discussed regarding the appearance of the figures. 
@mathieuboudreau please check if everything is okay with the last two subplots (the two histograms) of the last figure.

**Comment by agahkarakuzu** [comment]
@FilipVel thank you, this looks really nice! For convenience, can you add [the link](https://notebook-factory.github.io/BayesianRepetoireOverlap) to the book in your comments for convenience? I have some comments: 

- [ ] In [Figure 6](https://notebook-factory.github.io/BayesianRepetoireOverlap/03Code/manusssscriptCalculations.html#Figure-6----Decrease-in-error-of-estimates-as-sampling-increases) `traces` do not have names, instead we see trace indexes when hovered. Can you give those traces (blue, organge, yellow histograms) labels if colors are coded in the figure caption?  

- [ ] The supplemental figure](https://notebook-factory.github.io/BayesianRepetoireOverlap/03Code/manusssscriptCalculations.html#Supplemental-Figure:-What-if-$n_a-\neq-n_b$-?) has `Select Here` as the default. Can you change it to this:

![image](https://user-images.githubusercontent.com/9632322/86607119-de02e800-bf76-11ea-85b7-ebdd67abb7bc.png)

**Comment by FilipVel** [comment]
Thanks @agahkarakuzu , I've updated the book with the changes made. 
I didn't quite understand the part with the link.  Were you thinking about adding the link to the book in a comment here, on this issue?

**Comment by agahkarakuzu** [comment]
> Were you thinking about adding the link to the book in a comment here, on this issue?

Yes, in just one of the comments to the book, nothing special :) I will take a look at your changes, see you in the meeting soon!

**Comment by FilipVel** [comment]
@mathieuboudreau , @agahkarakuzu Guys, 
Should I create separate notebooks for the unpublished figures, created with matplotlib, or should I leave them out of the book completely for now?

**Comment by mathieuboudreau** [comment]
If they aren't the figures in the paper, I would leave them out of the Jupyter Book for now

**Comment by FilipVel** [comment]
So I think I've done everything that we discussed today. You can check out the results [here](https://notebook-factory.github.io/BayesianRepetoireOverlap/01Introduction/intro.html)
Please update me if I need to make some other changes. 

Edit: I actually added the supplemental figure, as it was somewhat present in the paper, as supporting information.

**Comment by mathieuboudreau** [comment]
@FilipVel It looks great! The only thing that I'd recommend (and this goes for @zelenkastiot as well) is to have text labels next to the +- code collapse buttons to explain what each block is (e.g. "Code imports", "Functions" "Script" "Plot"), and to also include the figure captions that are inside the paper for each of them, e.g.:

<img width="1067" alt="Capture d’écran 2020-07-07 à 15 30 05" src="https://user-images.githubusercontent.com/1421029/86826184-c2770a80-c066-11ea-98a5-22b4bb350319.png">

**Comment by mathieuboudreau** [comment]
@FilipVel We (@zelenkastiot and @TommyBoshkovski to be exact) made the additional changes needed before sending it to the authors today - so no need to work on this on the weekend on your end!

**Comment by FilipVel** [comment]
Okay, great, thanks guys!

**Comment by agahkarakuzu** [comment]
Just trying something

[AB#6](https://dev.azure.com/notebookfactory/2119ea02-b502-4736-8b5a-f416d46e15d2/_workitems/edit/6)

**Comment by mathieuboudreau** [comment]
Meeting to do list:

* [ ] Use Jupyter Lab
* [ ] Put all code in one cell
* [ ] Look into a way to reduce space between code cells and figures or text
* [ ] Explore different ways to visualize figures/code in a fork
