### ISSUE TITLE
"Myelin water fraction estimation using small‐tip fast recovery MRI"

### ISSUE THREAD

**Issue by zelenkastiot** [Notebook-Factory/assign#3]
Paper: https://onlinelibrary.wiley.com/doi/full/10.1002/mrm.28259
Code: https://github.com/StevenWhitaker/STFR-MWF
Note: Julia, Reproduces figures.

**Comment by zelenkastiot** [comment]
# To-Do 

* [ ] Create Jupyter Notebook with figures from scripts 
* [ ] Reproduce code in Binder with Julia Docker file
* [ ] Try maybe running [Pluto.jl](https://github.com/fonsp/Pluto.jl) notebook on Binder
