### ISSUE TITLE
"Pharmacokinetic modeling of dynamic contrast‐enhanced MRI using a reference region and input function tail"

### ISSUE THREAD

**Issue by zelenkastiot** [Notebook-Factory/assign#4]
Paper: https://onlinelibrary.wiley.com/doi/full/10.1002/mrm.27913
Code: https://github.com/MPUmri/RRIFT
Note: MATLAB. Reproduces ALL figures

**Comment by zelenkastiot** [comment]
# To-Do 

* [ ] Try to run figures on CodeOcean
* [ ] Create capsule that runs code
* [ ] Try installing SoS with MATLAB
* [ ] Try Plotly

**Comment by zelenkastiot** [comment]
This paper is assigned to: 
171150  - Бранко: @emorevival 
171015 - Давор: @ddimoski 

Repo for working: https://github.com/Notebook-Factory/RRFIT_notebooks 
Check your mails, I gave you privileges.
