### ISSUE TITLE
"Steady‐state imaging with inhomogeneous magnetization transfer contrast using multiband radiofrequency pulses”

### ISSUE THREAD

**Issue by zelenkastiot** [Notebook-Factory/assign#5]
Paper: 
Code: https://github.com/mriphysics/ihMT_steadystate
Note: MATLAB. Well documented, gave a git commit hash in the paper. [Q&A](https://blog.ismrm.org/2020/03/20/qa-with-shaihan-malik-and-daniel-west/)

**Comment by zelenkastiot** [comment]
# To-Do 

* [ ] Try to run figures on CodeOcean
* [ ] Create capsule that runs code
* [ ] Try installing SoS with MATLAB
* [ ] Try Plotly

**Comment by zelenkastiot** [comment]
This paper is assigned to:
171194 - Давид: @becutandavid 

Repo for working: https://github.com/Notebook-Factory/ihMT_notebooks
Check your mails, I gave you privileges.
